"use client";

import { useEffect, useRef, useState } from "react";
import Markdown from "./Markdown";

const KEY_PREFIX = "signal-pe:lesson-body:v1:";

type Cached = {
  body: string;
  generatedAt: string;
};

function cacheKey(courseSlug: string, lessonSlug: string) {
  return `${KEY_PREFIX}${courseSlug}:${lessonSlug}`;
}

function loadCached(courseSlug: string, lessonSlug: string): Cached | null {
  if (typeof window === "undefined") return null;
  const raw = window.localStorage.getItem(cacheKey(courseSlug, lessonSlug));
  if (!raw) return null;
  try {
    return JSON.parse(raw) as Cached;
  } catch {
    return null;
  }
}

function saveCached(courseSlug: string, lessonSlug: string, body: string) {
  if (typeof window === "undefined") return;
  const cached: Cached = { body, generatedAt: new Date().toISOString() };
  window.localStorage.setItem(cacheKey(courseSlug, lessonSlug), JSON.stringify(cached));
}

function clearCached(courseSlug: string, lessonSlug: string) {
  if (typeof window === "undefined") return;
  window.localStorage.removeItem(cacheKey(courseSlug, lessonSlug));
}

export default function LessonBody({
  courseSlug,
  lessonSlug,
}: {
  courseSlug: string;
  lessonSlug: string;
}) {
  const [body, setBody] = useState<string>("");
  const [generatedAt, setGeneratedAt] = useState<string | null>(null);
  const [streaming, setStreaming] = useState(false);
  const [error, setError] = useState("");
  const startedRef = useRef(false);

  useEffect(() => {
    const cached = loadCached(courseSlug, lessonSlug);
    if (cached) {
      setBody(cached.body);
      setGeneratedAt(cached.generatedAt);
    } else if (!startedRef.current) {
      startedRef.current = true;
      void generate();
    }
    // Reset on lesson change.
    return () => {
      startedRef.current = false;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [courseSlug, lessonSlug]);

  async function generate() {
    setStreaming(true);
    setError("");
    setBody("");
    setGeneratedAt(null);
    try {
      const res = await fetch("/api/lesson-body", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ courseSlug, lessonSlug }),
      });
      if (!res.ok || !res.body) {
        throw new Error(`HTTP ${res.status}`);
      }
      const reader = res.body.getReader();
      const decoder = new TextDecoder();
      let acc = "";
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        acc += decoder.decode(value, { stream: true });
        setBody(acc);
      }
      saveCached(courseSlug, lessonSlug, acc);
      setGeneratedAt(new Date().toISOString());
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setStreaming(false);
    }
  }

  function regenerate() {
    clearCached(courseSlug, lessonSlug);
    void generate();
  }

  return (
    <div className="space-y-4">
      <div className="flex items-baseline justify-between gap-3 flex-wrap">
        <div className="text-xs uppercase tracking-wide text-zinc-500">
          Lesson body
        </div>
        <div className="flex items-center gap-3">
          {generatedAt && (
            <span className="text-xs text-zinc-500">
              cached {new Date(generatedAt).toLocaleString()}
            </span>
          )}
          <button
            onClick={regenerate}
            disabled={streaming}
            className="text-xs underline text-zinc-600 dark:text-zinc-400 disabled:opacity-50"
          >
            {streaming ? "Generating…" : "Regenerate"}
          </button>
        </div>
      </div>

      {error && (
        <div className="text-sm text-rose-600 dark:text-rose-400">
          {error}. The lesson body comes from Claude — make sure{" "}
          <code>ANTHROPIC_API_KEY</code> is set in the deployment env.
        </div>
      )}

      {!body && streaming && (
        <div className="text-sm text-zinc-500 italic">Streaming from Claude…</div>
      )}

      {body && <Markdown source={body} />}

      <div className="pt-3 border-t border-zinc-200 dark:border-zinc-800 text-xs text-zinc-500">
        Original tutorial content generated by Claude — not copied from any
        external source. Cached locally in your browser. Click{" "}
        <em>Regenerate</em> if the explanation isn&apos;t landing.
      </div>
    </div>
  );
}
